services:
    jpsymfony.unique_attribute_validator:
        class: Jpsymfony\CoreBundle\Validator\Constraints\UniqueAttributeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: unique_attribute_validator }